version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/code/
    depends_on:
      - postgres
    environment:
      - PRIVATE_API_KEY=YOUR_KEY
      - PUBLIC_API_KEY=your_key
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5432:5432"