# Generated by Django 4.1.3 on 2022-11-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'Доллар США'), ('rub', 'Рассейске Рубль')], default='rub', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
