# Generated by Django 4.1.3 on 2022-11-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_currency_item_stripe_id_alter_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='stripe_id',
            new_name='stripe_price_id',
        ),
        migrations.AddField(
            model_name='item',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
